// Fetch Ebooks for Home Page
export const FETCH_EBOOKS_START = "FETCH_EBOOKS_START";
export const FETCH_EBOOKS_SUCCESS = "FETCH_EBOOKS_SUCCESS";
export const FETCH_EBOOKS_FAIL = "FETCH_EBOOKS_FAIL";

// Fetch Detail of Ebook
export const FETCH_DETAIL_OF_EBOOK_START = "FETCH_DETAIL_OF_EBOOK_START";
export const FETCH_DETAIL_OF_EBOOK_SUCCESS = "FETCH_DETAIL_OF_EBOOK_SUCCESS";
export const FETCH_DETAIL_OF_EBOOK_FAIL = "FETCH_DETAIL_OF_EBOOK_FAIL";

// Search Ebooks by Category
export const SEARCH_EBOOKS_BY_CATEGORY_START =
   "SEARCH_EBOOKS_BY_CATEGORY_START";
export const SEARCH_EBOOKS_BY_CATEGORY_SUCCESS =
   "SEARCH_EBOOKS_BY_CATEGORY_SUCCESS";
export const SEARCH_EBOOKS_BY_CATEGORY_FAIL = "SEARCH_EBOOKS_BY_CATEGORY_FAIL";

// Search Ebooks by Input Name
export const SEARCH_EBOOKS_BY_INPUT_NAME_START =
   "SEARCH_EBOOKS_BY_INPUT_NAME_START";
export const SEARCH_EBOOKS_BY_INPUT_NAME_SUCCESS =
   "SEARCH_EBOOKS_BY_INPUT_NAME_SUCCESS";
export const SEARCH_EBOOKS_BY_INPUT_NAME_FAIL =
   "SEARCH_EBOOKS_BY_INPUT_NAME_FAIL";

// Add Ebook
export const ADD_EBOOK_START = "ADD_EBOOK_START";
export const ADD_EBOOK_SUCCESS = "ADD_EBOOK_SUCCESS";
export const ADD_EBOOK_FAIL = "ADD_EBOOK_FAIL";

// For Comment
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

// Load user
export const LOAD_USER_START = "LOAD_USER_START";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

// For Authentication
// For Sign up
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

// For Sign in
export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

// For Log out
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
